### ISSUE TITLE
Move app window

### ISSUE THREAD

**Issue by fultonm** [G07cha/pomodoro#29]
There seems no way to move the app window after clicking the tray icon. Causing problems with my toolbar layout with vertical toolbars on a dual monitor set up
https://gyazo.com/af148904c75839355e7b27fe5b6a0c9c

**Comment by pedrostc** [comment]
+1 for this issue.
The app screen is barely
![pomodoro](https://cloud.githubusercontent.com/assets/636561/20468610/40cc442e-af66-11e6-9fd1-2b6e83633ff7.png)
 visible when using the windows task bar on the left side of the screen.

**Comment by G07cha** [comment]
Hi @fultonm, @pedrostc!

Thanks for reporting this problem, I'm actually never tested it's before, I did some research and turns out that default position for [menubar](https://github.com/maxogden/menubar) is top right or bottom right corner. I'll try to fix this in next few days and notify you when the new version with the fix will be ready!

**Comment by wildebaard** [comment]
+1. This is still an issue. 
After (almost exactly) one year, I'm not expecting a fix. But hey, surprise me!

**Comment by mikaoelitiana** [comment]
Hi guys, I made a fix for this one!! Happy new year by the way ;)

**Comment by G07cha** [comment]
Published [version 2.2.0](https://github.com/G07cha/pomodoro/releases/tag/v2.2.0) with support for a draggable window.
