### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by daniel-barrows** [G07cha/pomodoro#38]
Are there significant obstacles to creating a version for Linux, or have y'all just not gotten around to packaging it for Linux?

**Comment by G07cha** [comment]
Hi @daniel-barrows, there are no problems in packaging the application for Linux, in a matter of a fact, you can do it yourself, if you wish, by pulling the repo, installing dependencies and running `./node_modules/.bin/build --linux` command. 

The reasoning behind the absence of Linux binary in releases is because of partial Linux support by [menubar](https://github.com/maxogden/menubar), our core dependencies. This may result in incorrect behavior on some Linux distros.
